### ISSUE TITLE
Background color is set to inherit instead of background color.

### ISSUE THREAD

**Issue by RahjIII** [mfontani/ansi2html#2]
Doesn't appear to be rendering bg colors correctly.  Cat attached test.txt file to color terminal, note that lines 2 and 3 of the output should have a blue background.  In html file (attached) the bg color is not set.

**Comment by RahjIII** [comment]
[test.ansi.gz](https://github.com/user-attachments/files/16119811/test.ansi.gz)
[test.html.gz](https://github.com/user-attachments/files/16119812/test.html.gz)

**Comment by RahjIII** [comment]
#!/bin/sh
echo "\e[38;2;0;0;170mBlue FG Text.\e[0m"
echo "\e[48;2;0;0;170mBlue BG Text.\e[0m"
echo "\e[48;2;0;0;170m\e[38;2;192;151;188mBlue FG/BG Text.\e[0m"

Try that.

**Comment by mfontani** [comment]
Ha! Didn't notice the issue @RahjIII. Should be fixed in master, now!
Thanks!
